= Laerning Tool
Author: Hugh Kaznowski
Date: 2023/07/15

== Introduction

Laerning Tool is an API that provides access to learning environments.
This is useful for various scenarios

Obvious (scholarly) uses:

- learning languages
- learning topics (such as electro dynamics)
- learning maps
- learning geo-policital statistics
- learning historic events

Non-obvious uses:

- learning rules to a complex game
- learning a style of writing
- fun quizzes (trivia, jackbox-esque, made up stuff)
- reinforcing process or exercises ("how to build and deploy this project", "how to remember the flow of thought for a presentation")
- reinforcing the key points from books you read

There are many more.
Any time you would have said "ah, I should put some effort into getting better at this!", this software should be the answer.
The datasets should be available online so others can use the data created!

== OpenAPI specification

There is an OpenAPI specification and associated SwaggerUI interface to get to grips with the engine easier.

You can access an interactive API via the normal http://localhost:3000/swagger-ui/#/[/swagger-ui] path.

The spec itself is available at the http://localhost:3000/api-docs/openapi.json[/api-docs/openapi.json] path, if you are generating clients for this engine.


== Diagrams

There are some helpful diagrams in the repository.
They have the extension `.graphml` and can be opened with yEd chart editor.


