= Laerning Tool
Author: Hugh Kaznowski
Date: 2023/07/15

image:https://github.com/phughk/laerning-tool/actions/workflows/rust.yml/badge.svg[Rust, link=https://github.com/phughk/laerning-tool/actions/workflows/rust.yml]
image:https://img.shields.io/github/license/phughk/laerning-tool[GitHub]

image:https://img.shields.io/github/commit-activity/t/phughk/laerning-tool[GitHub commit activity (branch)]
image:https://img.shields.io/github/commit-activity/y/phughk/laerning-tool[GitHub commit activity (branch)]
image:https://img.shields.io/github/commit-activity/m/phughk/laerning-tool[GitHub commit activity (branch)]

image:https://img.shields.io/github/issues/phughk/laerning-tool[GitHub issues]
image:https://img.shields.io/github/issues-pr/phughk/laerning-tool[GitHub pull requests]
image:https://img.shields.io/github/contributors/phughk/laerning-tool[GitHub contributors]

== Introduction

Laerning Tool is an API that provides access to learning environments.
This is useful for various scenarios

Obvious (scholarly) uses:

- learning languages
- learning topics (such as electro dynamics)
- learning maps
- learning geo-policital statistics
- learning historic events

Non-obvious uses:

- learning rules to a complex game
- learning a style of writing
- fun quizzes (trivia, jackbox-esque, made up stuff)
- reinforcing process or exercises ("how to build and deploy this project", "how to remember the flow of thought for a presentation")
- reinforcing the key points from books you read

There are many more.
Any time you would have said "ah, I should put some effort into getting better at this!", this software should be the answer.
The datasets should be available online so others can use the data created!

== OpenAPI specification

There is an OpenAPI specification and associated SwaggerUI interface to get to grips with the engine easier.

You can access an interactive API via the normal http://localhost:3000/swagger-ui/#/[/swagger-ui] path.

The spec itself is available at the http://localhost:3000/api-docs/openapi.json[/api-docs/openapi.json] path, if you are generating clients for this engine.

== XML Format

The learning modules (dataset) are a custom format that complies with XML standard.
There is an XML Schema Definition declared in `laerning-module.xsd`.
You can link it at the top of your XML files (like the ones in `data/`) to have it checked for correctness in your editor.

== Diagrams

There are some helpful diagrams in the repository.
They have the extension `.graphml` and can be opened with https://www.yworks.com/products/yed[yEd graph editor].

== Frequently Asked Questions

=== How do I run/test/build from source

This is a standard cargo project.
You can run the standard commands.

```
cargo run
cargo test
cargo build --release
```

You can find pre-made releases in the https://github.com/phughk/laerning-tool/releases[releases tab] to the right of the GitHub page.

=== How do I run the binary on Mac

```
sudo spctl --master-disable
./laerning-tool
sudo spctl --master-enable
```

Be careful with what you run from the internet;
The above disables your Mac's security temporarily to bypass safety checks.



